version: "3.5"
services:
  postgres:
    image: nest-postgres
    hostname: nest-postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    container_name: nest-postgres
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
      - ./postgres-db/:/docker-entrypoint-initdb.d/
    ports:
      - "$POSTGRES_PORT:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: nest-pgadmin4
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    ports:
      - "$PGADMIN_PORT:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
  postgres-db:
