version: "3.5"
services:
  postgres:
    image: nest-postgres
    hostname: $POSTGRES_HOST
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    container_name: $POSTGRES_HOST
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
      - ./postgres-db/:/docker-entrypoint-initdb.d/
    ports:
      - "$POSTGRES_PORT:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: nest-pgadmin4
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    ports:
      - "$PGADMIN_PORT:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  server:
    build:
      context: .
      dockerfile: ./nest-server-v2/Dockerfile
    container_name: nest-server-v2
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./nest-server-v2/:/app/

volumes:
  local_pgdata:
  pgadmin-data:
  postgres-db:
